spring:
  security:
    jwt:
      secret-key: "d"
  application:
    name: reservation
  datasource:
    url: jdbc:postgresql://localhost:5432/reservation
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect